name: BatchFile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  
jobs:
  build:
  
    runs-on: ubuntu-latest
      - name:Build
      run:mvn --batch-mode _DskipTests package
      
      - name:Test
      run:mvn --batch-mode -Dmaven.test.failure.ignore=true test
      

      
      
