name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn -B test --file pom.xml
        
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: "**/test-results.trx"
          reporter: java-junit
          fail-on-error: true

